

export const actionTypes = {
    SET_CONNECTED: 'SET_CONNECTED',
    SET_STOMP_CLIENT: 'SET_STOMP_CLIENT',
    ADD_MESSAGE: 'ADD_MESSAGE',
    ADD_ROOM: 'ADD_ROOM',
    SET_ROOM: 'SET_ROOM',
    SET_MESSAGE: 'SET_MESSAGE',
    SET_MESSAGES: 'SET_MESSAGES'
};